export const GET_BABYSITTERS = 'GET_BABYSITTERS';
export const GET_BABYSITTERS_LOCATION = 'GET_BABYSITTERS_LOCATION';
export const SELECT_BABYSITTER = 'SELECT_BABYSITTER';
export const LOADING = 'LOADING_BABYSITTERS';
export const ERROR = 'ERROR_BABYSITTERS';