export const SET_SERVICE_FORM = 'SET_SERVICE_FORM';
export const REGISTER_SERVICE = 'REGISTER_SERVICE';
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICE = 'GET_SERVICE';
export const START_SERVICE = 'START_SERVICE';
export const LOADING = 'LOADING_SERVICES';
export const ERROR = 'ERROR_SERVICES';